export {
  affiliateDepartmentSlugs,
  affiliateLeafSlugs,
  affiliateSubcategorySlugs,
  affiliateTaxonomy,
  findLeafBySlug,
  getLeafBySlug,
  isDepartmentLeafPair,
  isDepartmentSlug,
  isLeafSlug,
  isSubcategorySlug,
  legacyCategoryDestinations,
  listDepartments,
  listLeaves,
  listSubcategories,
  type AffiliateTaxonomy,
  type DepartmentDefinition,
  type DepartmentSlug,
  type LeafDefinition,
  type LeafSlug,
  type LegacyCategoryDestination,
  type SubcategoryDefinition,
  type SubcategorySlug,
} from "./affiliate-taxonomy";
